### PR TITLE
Feature/implementing spring core

### PR DESCRIPTION
**Pull request by yavlash-liza**
Implementing Spring Core

### CODE REVIEW

**Comment by kolyago-vladislav** [comment]
you should delete all file for configuration: 
- hibernate.cfg.xml
- HibernateUtil.java
- FlywayService.java
you shouldn't use xml configuration: delete context.xml

@Component - if you can use @Service, you should use @Service insted of @Companent

@RequaredArgConstructor will replace a visual constructor, use it

you should adopt your test using Spring

**Comment by kolyago-vladislav** [comment]
you don't understad how Spring works. Take more time, do research

**Comment by kolyago-vladislav** [comment]
image

**Comment by kolyago-vladislav** [comment]
this is incorect. Use another class for configuration. For example ApplicationConfiguration

**Review by kolyago-vladislav — APPROVED** [review]

**Review by yurueu-andrei — APPROVED** [review]

**Pull request merged**
